name: Lab 1 - Primer workflow basico

# Se ejecuta con cualquier push
on: [push]

jobs:
  ejecutar-comandos:
    # Restricción del lab: usar ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      # Step 1: Mensaje personalizado
      - name: Imprimir mensaje personalizado
        run: echo "¡Hola! He completado los requisitos de mi primer lab."

      # Step 2: Listar contenido del repo (sin usar actions externas)
      - name: Listar el contenido del espacio de trabajo
        run: ls 
